// @ts-check
import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: ['**/node_modules/**', '**/dist/**', '**/.next/**', '**/.turbo/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // NOTE: apps/admin has its own flat config (apps/admin/eslint.config.mjs,
    // generated by create-next-app) that ESLint resolves independently — this
    // root config is never merged with it when `pnpm --filter @starland/admin
    // lint` runs. The rule below is duplicated verbatim in
    // apps/admin/eslint.config.mjs for that app to actually be enforced. Keep
    // both in sync, or extract to a shared config package if a second app
    // (e.g. apps/portal) needs it too.
    files: ['apps/admin/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [{
          group: ['@starland/integrations-kitchen', '**/integrations/kitchen/**'],
          message:
            'Кухонна інтеграція заборонена в apps/admin. Її код живе тільки в portal і api — ' +
            'див. розділ 8 docs/specs/2026-07-31-starland-design.md.',
        }],
      }],
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
)
